# Generated by Django 5.2.10 on 2026-02-03 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InnovationPageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(default='Where Innovation Meets Scientific Proof', max_length=500)),
                ('hero_subtitle', models.TextField(default='Partner with MusB™ Research to design and execute rigorous research')),
                ('hero_cta_primary_text', models.CharField(default='Start an Innovation Discussion', max_length=100)),
                ('hero_cta_primary_link', models.CharField(default='/contact', max_length=200)),
                ('hero_cta_secondary_text', models.CharField(default='Explore Our Technologies', max_length=100)),
                ('hero_cta_secondary_link', models.CharField(default='#technologies', max_length=200)),
                ('show_industry_research_section', models.BooleanField(default=True)),
                ('show_concept_to_product_section', models.BooleanField(default=True)),
                ('show_technologies_section', models.BooleanField(default=True)),
                ('show_trust_grid_section', models.BooleanField(default=True)),
                ('show_final_cta_section', models.BooleanField(default=True)),
                ('industry_research_cta_text', models.CharField(blank=True, default='Run a Study With MusB™ Research', max_length=100)),
                ('concept_to_product_cta_text', models.CharField(blank=True, default='Submit Your Concept', max_length=100)),
                ('final_cta_text', models.CharField(blank=True, default='Start an Innovation Discussion', max_length=100)),
                ('study_inquiry_email', models.EmailField(default='sales@musbresearch.com', max_length=254)),
                ('concept_inquiry_email', models.EmailField(default='innovation@musbresearch.com', max_length=254)),
                ('partnership_inquiry_email', models.EmailField(default='partnerships@musbresearch.com', max_length=254)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Innovation Page Settings',
                'verbose_name_plural': 'Innovation Page Settings',
            },
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., IncreLac™', max_length=100)),
                ('tagline', models.CharField(help_text='e.g., GLP-1 Promoting Probiotics', max_length=200)),
                ('positioning', models.TextField(help_text='Short positioning statement')),
                ('focus_areas', models.JSONField(blank=True, default=list, help_text='List of focus areas as JSON array, e.g., ["Metabolic health", "GLP-1 signaling"]')),
                ('gradient_theme', models.CharField(choices=[('emerald-teal', 'Emerald to Teal'), ('blue-indigo', 'Blue to Indigo'), ('purple-pink', 'Purple to Pink'), ('cyan-blue', 'Cyan to Blue'), ('orange-red', 'Orange to Red')], default='cyan-blue', max_length=50)),
                ('icon_name', models.CharField(default='TrendingUp', help_text='Lucide icon name (e.g., TrendingUp, FlaskConical, Shield)', max_length=50)),
                ('display_order', models.IntegerField(default=0, help_text='Lower numbers appear first')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Technology',
                'verbose_name_plural': 'Technologies',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SponsorInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('company', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('inquiry_type', models.CharField(choices=[('run_study', 'Run a Study'), ('submit_concept', 'Submit Your Concept'), ('explore_technology', 'Explore Technology'), ('general', 'General Inquiry')], max_length=50)),
                ('message', models.TextField()),
                ('routed_to_email', models.EmailField(help_text='Email address this inquiry was routed to', max_length=254)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('is_processed', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, help_text='Internal notes')),
                ('technology', models.ForeignKey(blank=True, help_text='If inquiry is about a specific technology', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.technology')),
            ],
            options={
                'verbose_name': 'Sponsor Inquiry',
                'verbose_name_plural': 'Sponsor Inquiries',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='TechnologyDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('scientific_data', 'Scientific Data'), ('publication', 'Publication'), ('news', 'News & Updates'), ('flyer', 'Flyer / Marketing Asset'), ('other', 'Other')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='technology_documents/')),
                ('external_link', models.URLField(blank=True, help_text='Use if document is hosted externally')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('technology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='api.technology')),
            ],
            options={
                'verbose_name': 'Technology Document',
                'verbose_name_plural': 'Technology Documents',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
