# Generated by Django 5.2.10 on 2026-02-10 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_aboutpagesettings_advisor_careercategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpagesettings',
            name='core_values',
            field=models.JSONField(blank=True, default=list, help_text='JSON array of {icon, name, description}'),
        ),
        migrations.AddField(
            model_name='aboutpagesettings',
            name='final_cta_subtitle',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='aboutpagesettings',
            name='final_cta_title',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='aboutpagesettings',
            name='hero_description',
            field=models.TextField(blank=True, default="At MusB™ Research, we don't just run studies—we help you understand your product's strengths, limitations, and real-world impact so you can make the best scientific, business, and health decisions."),
        ),
        migrations.AddField(
            model_name='aboutpagesettings',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='about/'),
        ),
        migrations.AddField(
            model_name='aboutpagesettings',
            name='hero_tagline',
            field=models.CharField(blank=True, default='Scientist-Led Growth', max_length=100),
        ),
        migrations.AddField(
            model_name='aboutpagesettings',
            name='hero_title',
            field=models.CharField(blank=True, default='Your Science Partner for Evidence-Driven Growth', max_length=500),
        ),
        migrations.AddField(
            model_name='aboutpagesettings',
            name='mission_content',
            field=models.TextField(blank=True, default='To advance human health through rigorous, ethical, and innovative research that bridges scientific discovery with real-world impact.'),
        ),
        migrations.AddField(
            model_name='aboutpagesettings',
            name='mission_title',
            field=models.CharField(blank=True, default='Our Mission', max_length=200),
        ),
        migrations.AddField(
            model_name='aboutpagesettings',
            name='partner_content',
            field=models.TextField(blank=True, default='We operate as a seamless extension of your internal team, providing deep scientific expertise, operational agility, and end-to-end project management.'),
        ),
        migrations.AddField(
            model_name='aboutpagesettings',
            name='partner_features',
            field=models.JSONField(blank=True, default=list, help_text='JSON array of {icon, title, description}'),
        ),
        migrations.AddField(
            model_name='aboutpagesettings',
            name='partner_title',
            field=models.CharField(blank=True, default='Your Extended R&D Partner', max_length=300),
        ),
        migrations.AddField(
            model_name='aboutpagesettings',
            name='show_core_values_section',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='aboutpagesettings',
            name='show_mission_vision_section',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='aboutpagesettings',
            name='show_partner_section',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='aboutpagesettings',
            name='show_story_section',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='aboutpagesettings',
            name='show_three_ways_section',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='aboutpagesettings',
            name='story_content',
            field=models.TextField(blank=True, default='MusB™ Research was founded with a singular vision: to bridge the gap between groundbreaking scientific discovery and real-world health impact.'),
        ),
        migrations.AddField(
            model_name='aboutpagesettings',
            name='story_image',
            field=models.ImageField(blank=True, null=True, upload_to='about/'),
        ),
        migrations.AddField(
            model_name='aboutpagesettings',
            name='story_title',
            field=models.CharField(blank=True, default='Our Story', max_length=300),
        ),
        migrations.AddField(
            model_name='aboutpagesettings',
            name='three_ways_cards',
            field=models.JSONField(blank=True, default=list, help_text='JSON array of {icon, title, who, deliverables[], quote, cta_text, cta_link, color}'),
        ),
        migrations.AddField(
            model_name='aboutpagesettings',
            name='three_ways_subtitle',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='aboutpagesettings',
            name='three_ways_title',
            field=models.CharField(blank=True, default='Three Ways MusB™ Research Supports Your Program', max_length=300),
        ),
        migrations.AddField(
            model_name='aboutpagesettings',
            name='vision_content',
            field=models.TextField(blank=True, default='To be the most trusted name in translational and clinical research, setting the global standard for scientific integrity and innovation.'),
        ),
        migrations.AddField(
            model_name='aboutpagesettings',
            name='vision_title',
            field=models.CharField(blank=True, default='Our Vision', max_length=200),
        ),
    ]
