# Generated by Django 5.2.10 on 2026-02-11 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_aboutpagesettings_core_values_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacilitiesPageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(default='Facilities & Infrastructure Built for Sponsor-Ready Research', max_length=300)),
                ('hero_subtext_1', models.CharField(blank=True, default='Integrated, regulatory-compliant infrastructure supporting preclinical discovery through human clinical trials.', max_length=500)),
                ('hero_subtext_2', models.CharField(blank=True, default='Designed for scientific rigor, scalability, and decision-grade data.', max_length=500)),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='facilities/')),
                ('research_pillar_title', models.CharField(default='Research & Innovation', max_length=200)),
                ('research_pillar_desc', models.TextField(default='Preclinical and clinical infrastructure to validate mechanisms, efficacy, and safety with speed and rigor.')),
                ('lab_pillar_title', models.CharField(default='Central Laboratory Services', max_length=200)),
                ('lab_pillar_desc', models.TextField(default='Reliable, scalable biomarker and molecular testing with sponsor-ready workflows and documentation.')),
                ('bio_pillar_title', models.CharField(default='Biorepository', max_length=200)),
                ('bio_pillar_desc', models.TextField(default='Secure biospecimen processing, tracking, and storage to protect your samples and your future discoveries.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Facilities Page Settings',
                'verbose_name_plural': 'Facilities Page Settings',
            },
        ),
        migrations.CreateModel(
            name='FacilityModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pillar', models.CharField(choices=[('Research', 'Research & Innovation'), ('Lab', 'Central Laboratory Services'), ('Biorepository', 'Biorepository')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('one_line_summary', models.CharField(max_length=300)),
                ('description', models.TextField(help_text='Main accordion text')),
                ('micro_bullets', models.JSONField(default=list, help_text='List of strings')),
                ('image', models.ImageField(blank=True, null=True, upload_to='facilities/')),
                ('badge_label', models.CharField(blank=True, max_length=100)),
                ('layout', models.CharField(choices=[('TextLeft', 'Text Left / Image Right'), ('ImageLeft', 'Image Left / Text Right')], default='TextLeft', max_length=20)),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='FacilityPillar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(help_text='research, lab, biorepository', unique=True)),
                ('short_desc', models.TextField()),
                ('cta_text', models.CharField(max_length=100)),
                ('cta_link', models.CharField(max_length=200)),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='SuccessSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('icon', models.CharField(default='Star', max_length=50)),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='TrustBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('icon', models.CharField(default='ShieldCheck', max_length=50)),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
    ]
