# Generated by Django 5.2.10 on 2026-02-12 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_facilitiespagesettings_facilitymodule_facilitypillar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='benefit',
            field=models.CharField(blank=True, help_text='Short benefit text e.g. "No Cost Product & Report"', max_length=300),
        ),
        migrations.AddField(
            model_name='study',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text='List of short tags e.g. ["Remote", "Compensation"]'),
        ),
        migrations.AddField(
            model_name='study',
            name='type',
            field=models.CharField(choices=[('Virtual', 'Virtual'), ('On-site', 'On-site'), ('Hybrid', 'Hybrid')], default='On-site', max_length=20),
        ),
    ]
