# Generated by Django 5.2.10 on 2026-02-24 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_study_benefit_study_tags_study_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookletDownloadRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=50)),
                ('nda_agreed', models.BooleanField(default=False)),
                ('technology_name', models.CharField(blank=True, max_length=200)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Booklet Download Request',
                'verbose_name_plural': 'Booklet Download Requests',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
