# Generated by Django 6.0.2 on 2026-02-26 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_aboutpagesettings_id_alter_advisor_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='compensation',
            field=models.CharField(blank=True, help_text='e.g., "$50 - $200"', max_length=100),
        ),
        migrations.AddField(
            model_name='study',
            name='cta_button_link',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='study',
            name='cta_button_text',
            field=models.CharField(default='Check Eligibility', max_length=100),
        ),
        migrations.AddField(
            model_name='study',
            name='is_free_testing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='study',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
