# Generated by Django 6.0.2 on 2026-02-26 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_study_compensation_study_cta_button_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='study',
            name='compensation',
        ),
        migrations.RemoveField(
            model_name='study',
            name='cta_button_link',
        ),
        migrations.RemoveField(
            model_name='study',
            name='cta_button_text',
        ),
        migrations.AddField(
            model_name='study',
            name='compensation_range',
            field=models.CharField(blank=True, help_text='e.g. "$50 - $200"', max_length=100),
        ),
    ]
