# Generated by Django 6.0.2 on 2026-02-28 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_study_compensation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilitiespagesettings',
            name='bio_cta_primary_text',
            field=models.CharField(default='Explore Biorepository Support', max_length=100),
        ),
        migrations.AddField(
            model_name='facilitiespagesettings',
            name='bio_cta_secondary_text',
            field=models.CharField(default='Request Storage Pricing', max_length=100),
        ),
        migrations.AddField(
            model_name='facilitiespagesettings',
            name='bio_strip_primary_text',
            field=models.CharField(default='Schedule a Storage Consult', max_length=100),
        ),
        migrations.AddField(
            model_name='facilitiespagesettings',
            name='bio_strip_secondary_text',
            field=models.CharField(default='Download Sample Submission SOP', max_length=100),
        ),
        migrations.AddField(
            model_name='facilitiespagesettings',
            name='lab_cta_primary_text',
            field=models.CharField(default='Request Lab Services', max_length=100),
        ),
        migrations.AddField(
            model_name='facilitiespagesettings',
            name='lab_cta_secondary_text',
            field=models.CharField(default='Get a Sample Handling Guide', max_length=100),
        ),
        migrations.AddField(
            model_name='facilitiespagesettings',
            name='lab_strip_primary_text',
            field=models.CharField(default='Get a Testing Quote', max_length=100),
        ),
        migrations.AddField(
            model_name='facilitiespagesettings',
            name='lab_strip_secondary_text',
            field=models.CharField(default='Speak With Lab Director', max_length=100),
        ),
        migrations.AddField(
            model_name='facilitiespagesettings',
            name='research_cta_primary_text',
            field=models.CharField(default='Discuss a Research Plan', max_length=100),
        ),
        migrations.AddField(
            model_name='facilitiespagesettings',
            name='research_cta_secondary_text',
            field=models.CharField(default='See Example Study Designs', max_length=100),
        ),
        migrations.AddField(
            model_name='facilitiespagesettings',
            name='research_strip_primary_text',
            field=models.CharField(default='Start a Research Project', max_length=100),
        ),
        migrations.AddField(
            model_name='facilitiespagesettings',
            name='research_strip_secondary_text',
            field=models.CharField(default='Request a Feasibility Call', max_length=100),
        ),
    ]
