# Generated by Django 6.0.2 on 2026-02-28 12:45

import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_facilitiespagesettings_bio_cta_primary_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadForm',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_type', models.CharField(choices=[('Research', 'Research & Innovation'), ('Lab', 'Central Laboratory Services'), ('Biorepository', 'Biorepository'), ('General', 'General Inquiry')], max_length=50, unique=True)),
                ('destination_emails', models.TextField(help_text='Comma-separated list of emails')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Lead Form Configuration',
                'verbose_name_plural': 'Lead Form Configurations',
            },
        ),
    ]
