# Generated by Django 6.0.2 on 2026-03-01 14:37

import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_leadform'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacilityInquiry',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('company', models.CharField(blank=True, max_length=200)),
                ('interest', models.CharField(choices=[('Research & Innovation', 'Research & Innovation'), ('Central Laboratory Services', 'Central Laboratory Services'), ('Biorepository', 'Biorepository'), ('Not sure (Help me choose)', 'Not sure (Help me choose)')], max_length=100)),
                ('stage', models.CharField(max_length=100)),
                ('routed_to_email', models.EmailField(max_length=254)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Facility Inquiry',
                'verbose_name_plural': 'Facility Inquiries',
            },
        ),
        migrations.DeleteModel(
            name='LeadForm',
        ),
        migrations.RemoveField(
            model_name='facilitiespagesettings',
            name='bio_cta_primary_text',
        ),
        migrations.RemoveField(
            model_name='facilitiespagesettings',
            name='bio_cta_secondary_text',
        ),
        migrations.RemoveField(
            model_name='facilitiespagesettings',
            name='bio_strip_primary_text',
        ),
        migrations.RemoveField(
            model_name='facilitiespagesettings',
            name='bio_strip_secondary_text',
        ),
        migrations.RemoveField(
            model_name='facilitiespagesettings',
            name='lab_cta_primary_text',
        ),
        migrations.RemoveField(
            model_name='facilitiespagesettings',
            name='lab_cta_secondary_text',
        ),
        migrations.RemoveField(
            model_name='facilitiespagesettings',
            name='lab_strip_primary_text',
        ),
        migrations.RemoveField(
            model_name='facilitiespagesettings',
            name='lab_strip_secondary_text',
        ),
        migrations.RemoveField(
            model_name='facilitiespagesettings',
            name='research_cta_primary_text',
        ),
        migrations.RemoveField(
            model_name='facilitiespagesettings',
            name='research_cta_secondary_text',
        ),
        migrations.RemoveField(
            model_name='facilitiespagesettings',
            name='research_strip_primary_text',
        ),
        migrations.RemoveField(
            model_name='facilitiespagesettings',
            name='research_strip_secondary_text',
        ),
        migrations.AddField(
            model_name='facilitymodule',
            name='icon_name',
            field=models.CharField(default='Microscope', help_text='Lucide React icon name', max_length=50),
        ),
        migrations.AddField(
            model_name='facilitymodule',
            name='image_alt',
            field=models.CharField(blank=True, help_text='Alt text for 16:9 image', max_length=200),
        ),
    ]
