# Generated by Django 5.2.10 on 2026-02-10 14:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_title', models.CharField(default='Contact Us', max_length=200)),
                ('intro_text', models.TextField(default='We’re here to help. Reach out to design research collaborations, laboratory services, biorepository support, or participate in our clinical studies.')),
                ('show_map', models.BooleanField(default=True)),
                ('show_quick_links', models.BooleanField(default=True)),
                ('show_cta_band', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contact Page Settings',
                'verbose_name_plural': 'Contact Page Settings',
            },
        ),
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('organization', models.CharField(blank=True, max_length=200)),
                ('inquiry_type', models.CharField(choices=[('business', 'Business / Sponsorship'), ('research', 'Research Collaboration'), ('lab', 'Central Laboratory Services'), ('biorepository', 'Biorepository'), ('participation', 'Clinical Study Participation'), ('careers', 'Careers'), ('general', 'General Inquiry')], max_length=50)),
                ('message', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('is_processed', models.BooleanField(default=False)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes for tracking')),
            ],
            options={
                'verbose_name': 'Contact Submission',
                'verbose_name_plural': 'Contact Submissions',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
