# Generated by Django 5.2.10 on 2026-02-10 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactFormConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_label', models.CharField(default='Full Name', max_length=100)),
                ('email_label', models.CharField(default='Email Address', max_length=100)),
                ('company_label', models.CharField(default='Company / Organization', max_length=100)),
                ('phone_label', models.CharField(default='Phone Number', max_length=100)),
                ('inquiry_type_label', models.CharField(default='Reason for Inquiry', max_length=100)),
                ('message_label', models.CharField(default='Message', max_length=100)),
                ('is_company_required', models.BooleanField(default=False)),
                ('is_phone_required', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contact Form Configuration',
                'verbose_name_plural': 'Contact Form Configurations',
            },
        ),
        migrations.CreateModel(
            name='InquiryType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='e.g., Business / Sponsorship', max_length=100)),
                ('slug', models.SlugField(help_text='Unique identifier for frontend logic', unique=True)),
                ('recipient_email', models.EmailField(help_text='Where to send these inquiries', max_length=254)),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['display_order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('company', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('message', models.TextField()),
                ('routed_to', models.EmailField(blank=True, help_text='Email address this was sent to', max_length=254)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('is_processed', models.BooleanField(default=False)),
                ('admin_notes', models.TextField(blank=True)),
                ('inquiry_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contact.inquirytype')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.DeleteModel(
            name='ContactSubmission',
        ),
        migrations.RenameField(
            model_name='contactpagesettings',
            old_name='show_map',
            new_name='show_map_section',
        ),
        migrations.RenameField(
            model_name='contactpagesettings',
            old_name='show_quick_links',
            new_name='show_quick_links_section',
        ),
        migrations.AlterField(
            model_name='contactpagesettings',
            name='intro_text',
            field=models.TextField(default='Get in touch with us.'),
        ),
    ]
